///************************************************
/// Generated by: TuyenNT
/// Date: 13/07/2014 11:54:41
/// Goal: Create User Service Class for RPT_CHI_PHI_THEO_PHAP_NHAN
///************************************************
/// <summary>
/// Create User Service Class for RPT_CHI_PHI_THEO_PHAP_NHAN
/// </summary>

using System;
using BCTKDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BCTKUS{

public class US_RPT_CHI_PHI_THEO_PHAP_NHAN : US_Object
{
	private const string c_TableName = "RPT_CHI_PHI_THEO_PHAP_NHAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_PHAP_NHAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_PHAP_NHAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_PHAP_NHAN"] = value;
		}
	}

	public bool IsID_PHAP_NHANNull()	{
		return pm_objDR.IsNull("ID_PHAP_NHAN");
	}

	public void SetID_PHAP_NHANNull() {
		pm_objDR["ID_PHAP_NHAN"] = System.Convert.DBNull;
	}

	public string strMA_PHAP_NHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_PHAP_NHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_PHAP_NHAN"] = value;
		}
	}

	public bool IsMA_PHAP_NHANNull() 
	{
		return pm_objDR.IsNull("MA_PHAP_NHAN");
	}

	public void SetMA_PHAP_NHANNull() {
		pm_objDR["MA_PHAP_NHAN"] = System.Convert.DBNull;
	}

	public string strTEN_PHAP_NHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_PHAP_NHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_PHAP_NHAN"] = value;
		}
	}

	public bool IsTEN_PHAP_NHANNull() 
	{
		return pm_objDR.IsNull("TEN_PHAP_NHAN");
	}

	public void SetTEN_PHAP_NHANNull() {
		pm_objDR["TEN_PHAP_NHAN"] = System.Convert.DBNull;
	}

	public decimal dcTONG_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TONG_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TONG_TIEN"] = value;
		}
	}

	public bool IsTONG_TIENNull()	{
		return pm_objDR.IsNull("TONG_TIEN");
	}

	public void SetTONG_TIENNull() {
		pm_objDR["TONG_TIEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_RPT_CHI_PHI_THEO_PHAP_NHAN() 
	{
		pm_objDS = new DS_RPT_CHI_PHI_THEO_PHAP_NHAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_RPT_CHI_PHI_THEO_PHAP_NHAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_RPT_CHI_PHI_THEO_PHAP_NHAN(decimal i_dbID) 
	{
		pm_objDS = new DS_RPT_CHI_PHI_THEO_PHAP_NHAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
    public void fillDatasetByProc(DS_RPT_CHI_PHI_THEO_PHAP_NHAN ip_ds, DateTime ip_from_date, DateTime ip_to_date) {
        CStoredProc v_proc = new CStoredProc("pr_rpt_chi_phi_theo_phap_nhan");
        v_proc.addDatetimeInputParam("@FROM_DATE", ip_from_date);
        v_proc.addDatetimeInputParam("@TO_DATE", ip_to_date);
        v_proc.fillDataSetByCommand(this, ip_ds);
    }
	}
}
