///************************************************
/// Generated by: TuDM
/// Date: 23/09/2014 09:36:10
/// Goal: Create User Service Class for V_GD_VAN_THU_ALL
///************************************************
/// <summary>
/// Create User Service Class for V_GD_VAN_THU_ALL
/// </summary>

using System;
using BCTKDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BCTKUS
{

    public class US_V_GD_VAN_THU_ALL : US_Object
    {
        private const string c_TableName = "V_GD_VAN_THU_ALL";
        #region "Public Properties"
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public decimal dcID_PHAP_NHAN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_PHAP_NHAN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_PHAP_NHAN"] = value;
            }
        }

        public bool IsID_PHAP_NHANNull()
        {
            return pm_objDR.IsNull("ID_PHAP_NHAN");
        }

        public void SetID_PHAP_NHANNull()
        {
            pm_objDR["ID_PHAP_NHAN"] = System.Convert.DBNull;
        }

        public string strSO_CV_DEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "SO_CV_DEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["SO_CV_DEN"] = value;
            }
        }

        public bool IsSO_CV_DENNull()
        {
            return pm_objDR.IsNull("SO_CV_DEN");
        }

        public void SetSO_CV_DENNull()
        {
            pm_objDR["SO_CV_DEN"] = System.Convert.DBNull;
        }

        public string strNOI_GUI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NOI_GUI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NOI_GUI"] = value;
            }
        }

        public bool IsNOI_GUINull()
        {
            return pm_objDR.IsNull("NOI_GUI");
        }

        public void SetNOI_GUINull()
        {
            pm_objDR["NOI_GUI"] = System.Convert.DBNull;
        }

        public string strTEN_LOAI_VA_TRICH_YEU_ND
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_LOAI_VA_TRICH_YEU_ND", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_LOAI_VA_TRICH_YEU_ND"] = value;
            }
        }

        public bool IsTEN_LOAI_VA_TRICH_YEU_NDNull()
        {
            return pm_objDR.IsNull("TEN_LOAI_VA_TRICH_YEU_ND");
        }

        public void SetTEN_LOAI_VA_TRICH_YEU_NDNull()
        {
            pm_objDR["TEN_LOAI_VA_TRICH_YEU_ND"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_THANG_TREN_CONG_VAN
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_THANG_TREN_CONG_VAN", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_THANG_TREN_CONG_VAN"] = value;
            }
        }

        public bool IsNGAY_THANG_TREN_CONG_VANNull()
        {
            return pm_objDR.IsNull("NGAY_THANG_TREN_CONG_VAN");
        }

        public void SetNGAY_THANG_TREN_CONG_VANNull()
        {
            pm_objDR["NGAY_THANG_TREN_CONG_VAN"] = System.Convert.DBNull;
        }

        public decimal dcID_NOI_NGUOI_NHAN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NOI_NGUOI_NHAN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NOI_NGUOI_NHAN"] = value;
            }
        }

        public bool IsID_NOI_NGUOI_NHANNull()
        {
            return pm_objDR.IsNull("ID_NOI_NGUOI_NHAN");
        }

        public void SetID_NOI_NGUOI_NHANNull()
        {
            pm_objDR["ID_NOI_NGUOI_NHAN"] = System.Convert.DBNull;
        }

        public decimal dcID_TRANG_THAI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_TRANG_THAI"] = value;
            }
        }

        public bool IsID_TRANG_THAINull()
        {
            return pm_objDR.IsNull("ID_TRANG_THAI");
        }

        public void SetID_TRANG_THAINull()
        {
            pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
        }

        public string strNGUOI_LAP
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_LAP"] = value;
            }
        }

        public bool IsNGUOI_LAPNull()
        {
            return pm_objDR.IsNull("NGUOI_LAP");
        }

        public void SetNGUOI_LAPNull()
        {
            pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
        }

        public string strLINK_SCAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "LINK_SCAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["LINK_SCAN"] = value;
            }
        }

        public bool IsLINK_SCANNull()
        {
            return pm_objDR.IsNull("LINK_SCAN");
        }

        public void SetLINK_SCANNull()
        {
            pm_objDR["LINK_SCAN"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_CONG_VAN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_CONG_VAN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_CONG_VAN"] = value;
            }
        }

        public bool IsID_LOAI_CONG_VANNull()
        {
            return pm_objDR.IsNull("ID_LOAI_CONG_VAN");
        }

        public void SetID_LOAI_CONG_VANNull()
        {
            pm_objDR["ID_LOAI_CONG_VAN"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_LAP
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_LAP", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_LAP"] = value;
            }
        }

        public bool IsNGAY_LAPNull()
        {
            return pm_objDR.IsNull("NGAY_LAP");
        }

        public void SetNGAY_LAPNull()
        {
            pm_objDR["NGAY_LAP"] = System.Convert.DBNull;
        }

        public string strSO_VA_KY_HIEU
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "SO_VA_KY_HIEU", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["SO_VA_KY_HIEU"] = value;
            }
        }

        public bool IsSO_VA_KY_HIEUNull()
        {
            return pm_objDR.IsNull("SO_VA_KY_HIEU");
        }

        public void SetSO_VA_KY_HIEUNull()
        {
            pm_objDR["SO_VA_KY_HIEU"] = System.Convert.DBNull;
        }

        public string strNGUOI_KY
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_KY", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_KY"] = value;
            }
        }

        public bool IsNGUOI_KYNull()
        {
            return pm_objDR.IsNull("NGUOI_KY");
        }

        public void SetNGUOI_KYNull()
        {
            pm_objDR["NGUOI_KY"] = System.Convert.DBNull;
        }

        public string strNOI_NHAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NOI_NHAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NOI_NHAN"] = value;
            }
        }

        public bool IsNOI_NHANNull()
        {
            return pm_objDR.IsNull("NOI_NHAN");
        }

        public void SetNOI_NHANNull()
        {
            pm_objDR["NOI_NHAN"] = System.Convert.DBNull;
        }

        public decimal dcID_NGUOI_NHAN_BAN_LUU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_NHAN_BAN_LUU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NGUOI_NHAN_BAN_LUU"] = value;
            }
        }

        public bool IsID_NGUOI_NHAN_BAN_LUUNull()
        {
            return pm_objDR.IsNull("ID_NGUOI_NHAN_BAN_LUU");
        }

        public void SetID_NGUOI_NHAN_BAN_LUUNull()
        {
            pm_objDR["ID_NGUOI_NHAN_BAN_LUU"] = System.Convert.DBNull;
        }

        public string strDANH_SACH_EMAIL_BAN_HANH
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DANH_SACH_EMAIL_BAN_HANH", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DANH_SACH_EMAIL_BAN_HANH"] = value;
            }
        }

        public bool IsDANH_SACH_EMAIL_BAN_HANHNull()
        {
            return pm_objDR.IsNull("DANH_SACH_EMAIL_BAN_HANH");
        }

        public void SetDANH_SACH_EMAIL_BAN_HANHNull()
        {
            pm_objDR["DANH_SACH_EMAIL_BAN_HANH"] = System.Convert.DBNull;
        }

        public string strDANH_SACH_EMAIL_XAC_NHAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DANH_SACH_EMAIL_XAC_NHAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DANH_SACH_EMAIL_XAC_NHAN"] = value;
            }
        }

        public bool IsDANH_SACH_EMAIL_XAC_NHANNull()
        {
            return pm_objDR.IsNull("DANH_SACH_EMAIL_XAC_NHAN");
        }

        public void SetDANH_SACH_EMAIL_XAC_NHANNull()
        {
            pm_objDR["DANH_SACH_EMAIL_XAC_NHAN"] = System.Convert.DBNull;
        }

        public string strGHI_CHU
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["GHI_CHU"] = value;
            }
        }

        public bool IsGHI_CHUNull()
        {
            return pm_objDR.IsNull("GHI_CHU");
        }

        public void SetGHI_CHUNull()
        {
            pm_objDR["GHI_CHU"] = System.Convert.DBNull;
        }

        public string strMA_PHAP_NHAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_PHAP_NHAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_PHAP_NHAN"] = value;
            }
        }

        public bool IsMA_PHAP_NHANNull()
        {
            return pm_objDR.IsNull("MA_PHAP_NHAN");
        }

        public void SetMA_PHAP_NHANNull()
        {
            pm_objDR["MA_PHAP_NHAN"] = System.Convert.DBNull;
        }

        public string strTEN_PHAP_NHAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_PHAP_NHAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_PHAP_NHAN"] = value;
            }
        }

        public bool IsTEN_PHAP_NHANNull()
        {
            return pm_objDR.IsNull("TEN_PHAP_NHAN");
        }

        public void SetTEN_PHAP_NHANNull()
        {
            pm_objDR["TEN_PHAP_NHAN"] = System.Convert.DBNull;
        }

        public string strNOI_NGUOI_NHAN_MPB
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NOI_NGUOI_NHAN_MPB", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NOI_NGUOI_NHAN_MPB"] = value;
            }
        }

        public bool IsNOI_NGUOI_NHAN_MPBNull()
        {
            return pm_objDR.IsNull("NOI_NGUOI_NHAN_MPB");
        }

        public void SetNOI_NGUOI_NHAN_MPBNull()
        {
            pm_objDR["NOI_NGUOI_NHAN_MPB"] = System.Convert.DBNull;
        }

        public string strNOI_NGUOI_NHAN_TPB
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NOI_NGUOI_NHAN_TPB", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NOI_NGUOI_NHAN_TPB"] = value;
            }
        }

        public bool IsNOI_NGUOI_NHAN_TPBNull()
        {
            return pm_objDR.IsNull("NOI_NGUOI_NHAN_TPB");
        }

        public void SetNOI_NGUOI_NHAN_TPBNull()
        {
            pm_objDR["NOI_NGUOI_NHAN_TPB"] = System.Convert.DBNull;
        }

        public string strNGUOI_NHAN__BAN_LUU_MPB
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN__BAN_LUU_MPB", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_NHAN__BAN_LUU_MPB"] = value;
            }
        }

        public bool IsNGUOI_NHAN__BAN_LUU_MPBNull()
        {
            return pm_objDR.IsNull("NGUOI_NHAN__BAN_LUU_MPB");
        }

        public void SetNGUOI_NHAN__BAN_LUU_MPBNull()
        {
            pm_objDR["NGUOI_NHAN__BAN_LUU_MPB"] = System.Convert.DBNull;
        }

        public string strNGUOI_NHAN__BAN_LUU_TPB
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN__BAN_LUU_TPB", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_NHAN__BAN_LUU_TPB"] = value;
            }
        }

        public bool IsNGUOI_NHAN__BAN_LUU_TPBNull()
        {
            return pm_objDR.IsNull("NGUOI_NHAN__BAN_LUU_TPB");
        }

        public void SetNGUOI_NHAN__BAN_LUU_TPBNull()
        {
            pm_objDR["NGUOI_NHAN__BAN_LUU_TPB"] = System.Convert.DBNull;
        }

        public string strTRANG_THAI_ML
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TRANG_THAI_ML", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TRANG_THAI_ML"] = value;
            }
        }

        public bool IsTRANG_THAI_MLNull()
        {
            return pm_objDR.IsNull("TRANG_THAI_ML");
        }

        public void SetTRANG_THAI_MLNull()
        {
            pm_objDR["TRANG_THAI_ML"] = System.Convert.DBNull;
        }

        public string strLOAI_CONG_BAN_ML
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "LOAI_CONG_BAN_ML", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["LOAI_CONG_BAN_ML"] = value;
            }
        }

        public bool IsLOAI_CONG_BAN_MLNull()
        {
            return pm_objDR.IsNull("LOAI_CONG_BAN_ML");
        }

        public void SetLOAI_CONG_BAN_MLNull()
        {
            pm_objDR["LOAI_CONG_BAN_ML"] = System.Convert.DBNull;
        }

        #endregion
        #region "Init Functions"
        public US_V_GD_VAN_THU_ALL()
        {
            pm_objDS = new DS_V_GD_VAN_THU_ALL();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_GD_VAN_THU_ALL(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_GD_VAN_THU_ALL(decimal i_dbID)
        {
            pm_objDS = new DS_V_GD_VAN_THU_ALL();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion

        #region "Additional"
        public void Search(DS_V_GD_VAN_THU_ALL op_ds, decimal ip_dc_id_phap_nhan
            , decimal ip_dc_id_loai_cong_van, DateTime ip_dat_tu_ngay, DateTime ip_dat_den_ngay
            , string ip_str_tu_khoa)
        {
            CStoredProc v_sp = new CStoredProc("pr_v_gd_van_thu_all_search");
            v_sp.addDecimalInputParam("@ip_dc_id_phap_nhan", ip_dc_id_phap_nhan);
            v_sp.addDecimalInputParam("@ip_dc_id_loai_cong_van", ip_dc_id_loai_cong_van);
            v_sp.addDatetimeInputParam("@ip_dat_tu_ngay", ip_dat_tu_ngay);
            v_sp.addDatetimeInputParam("@ip_dat_den_ngay", ip_dat_den_ngay);
            v_sp.addNVarcharInputParam("@ip_str_tu_khoa", ip_str_tu_khoa);
            v_sp.fillDataSetByCommand(this, op_ds);
        }

        #endregion
    }
}

