///************************************************
/// Generated by: HuyTD
/// Date: 27/06/2014 10:46:28
/// Goal: Create User Service Class for TONG_HOP_CPN_THEO_PHONG_BAN
///************************************************
/// <summary>
/// Create User Service Class for TONG_HOP_CPN_THEO_PHONG_BAN
/// </summary>

using System;
using BCTKDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BCTKUS{

public class US_TONG_HOP_CPN_THEO_PHONG_BAN : US_Object
{
	private const string c_TableName = "TONG_HOP_CPN_THEO_PHONG_BAN";
#region "Public Properties"
	public string strMA_PHONG_BAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_PHONG_BAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_PHONG_BAN"] = value;
		}
	}

	public bool IsMA_PHONG_BANNull() 
	{
		return pm_objDR.IsNull("MA_PHONG_BAN");
	}

	public void SetMA_PHONG_BANNull() {
		pm_objDR["MA_PHONG_BAN"] = System.Convert.DBNull;
	}

	public string strTEN_PHONG_BAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_PHONG_BAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_PHONG_BAN"] = value;
		}
	}

	public bool IsTEN_PHONG_BANNull() 
	{
		return pm_objDR.IsNull("TEN_PHONG_BAN");
	}

	public void SetTEN_PHONG_BANNull() {
		pm_objDR["TEN_PHONG_BAN"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_GUI
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_GUI", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_GUI"] = value;
		}
	}

	public bool IsNGAY_GUINull()
	{
		return pm_objDR.IsNull("NGAY_GUI");
	}

	public void SetNGAY_GUINull()
	{
		pm_objDR["NGAY_GUI"] = System.Convert.DBNull;
	}

	public string strSO_BILL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_BILL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_BILL"] = value;
		}
	}

	public bool IsSO_BILLNull() 
	{
		return pm_objDR.IsNull("SO_BILL");
	}

	public void SetSO_BILLNull() {
		pm_objDR["SO_BILL"] = System.Convert.DBNull;
	}

	public string strNGUOI_GUI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_GUI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_GUI"] = value;
		}
	}

	public bool IsNGUOI_GUINull() 
	{
		return pm_objDR.IsNull("NGUOI_GUI");
	}

	public void SetNGUOI_GUINull() {
		pm_objDR["NGUOI_GUI"] = System.Convert.DBNull;
	}

	public string strNGUOI_NHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_NHAN"] = value;
		}
	}

	public bool IsNGUOI_NHANNull() 
	{
		return pm_objDR.IsNull("NGUOI_NHAN");
	}

	public void SetNGUOI_NHANNull() {
		pm_objDR["NGUOI_NHAN"] = System.Convert.DBNull;
	}

	public string strTRANG_THAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRANG_THAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRANG_THAI"] = value;
		}
	}

	public bool IsTRANG_THAINull() 
	{
		return pm_objDR.IsNull("TRANG_THAI");
	}

	public void SetTRANG_THAINull() {
		pm_objDR["TRANG_THAI"] = System.Convert.DBNull;
	}

	public string strTRONG_NUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRONG_NUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRONG_NUOC"] = value;
		}
	}

	public bool IsTRONG_NUOCNull() 
	{
		return pm_objDR.IsNull("TRONG_NUOC");
	}

	public void SetTRONG_NUOCNull() {
		pm_objDR["TRONG_NUOC"] = System.Convert.DBNull;
	}

	public string strNUOC_NGOAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NUOC_NGOAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NUOC_NGOAI"] = value;
		}
	}

	public bool IsNUOC_NGOAINull() 
	{
		return pm_objDR.IsNull("NUOC_NGOAI");
	}

	public void SetNUOC_NGOAINull() {
		pm_objDR["NUOC_NGOAI"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_TONG_HOP_CPN_THEO_PHONG_BAN() 
	{
		pm_objDS = new DS_V_TONG_HOP_CPN_THEO_PHONG_BAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_TONG_HOP_CPN_THEO_PHONG_BAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_TONG_HOP_CPN_THEO_PHONG_BAN(decimal i_dbID) 
	{
		pm_objDS = new DS_V_TONG_HOP_CPN_THEO_PHONG_BAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


    public void FillDatasetSearch(DS_V_TONG_HOP_CPN_THEO_PHONG_BAN ip_v_ds, string ip_v_str_tu_khoa, decimal ip_v_id_phong_ban, DateTime ip_v_dt_tu_ngay, DateTime ip_v_dt_den_ngay)
    {
        CStoredProc v_stored_proc = new CStoredProc("pr_TONG_HOP_CPN_THEO_PHONG_BAN_Search");
        v_stored_proc.addNVarcharInputParam("@TU_KHOA", ip_v_str_tu_khoa);
        v_stored_proc.addDecimalInputParam("@ID_PHONG_BAN", ip_v_id_phong_ban);
        v_stored_proc.addDatetimeInputParam("@TU_NGAY", ip_v_dt_tu_ngay);
        v_stored_proc.addDatetimeInputParam("@DEN_NGAY", ip_v_dt_den_ngay);
        v_stored_proc.fillDataSetByCommand(this, ip_v_ds);
    }
}
}
